### PR TITLE
Add random tests, explanations, checker, cover, local visualization

### PR DESCRIPTION
**Pull request by Philippe-Cholet**
It requires a file named `my_solution.py` with a function named `inscribe` in it, solution of the problem.
On local machine it requires `matplotlib` package to visualize points.

I did not want to impose my solution to the problem. So I didn't add the file `my_solution.py`.

### CODE REVIEW

**Comment by Philippe-Cholet** [comment]
I'm still thinking about it. kurosawa would probably propose visualization at some point. So it would be nice for that visualization to know the coordinates of the smallest rectangle. Then tests should look like `{'input': [...], 'answer': ..., 'explanation': ...}`.

You would have to add explanations to current tests. And the solution in `my_solution` would have to compute the area and the coordinates of the rectangle, which my perso solution does now (I did it for matplotlib visualization).

**Comment by Philippe-Cholet** [comment]
Now the user don't have to round the result in "Check" part. The checker look if the result is close enough to the answer.

**Comment by Philippe-Cholet** [comment]
Results (with ±0.001 precision) in initial code too now.

**Review by quarkov — APPROVED** [review]

**Comment by Philippe-Cholet** [comment]
Do you want me to create `verification/my_solution.py` ?

**Comment by Philippe-Cholet** [comment]
The `.gitignore` file hide the files we don't want to sync on github like `__pycache__` folder.

My solution here provides both area and rectangle's coordinates for tests' explanations. So I add explanation to random tests:
* It will be useful for kurosawa visualization.
* But **12 first tests does not have explanations yet**.
* On local machine, we can now visualize rectangles thanks to matplotlib package.

**Comment by Philippe-Cholet** [comment]
Well now, there are all explanations for visualizations.
Last point I see is that maybe kurosawa would like rectangles to repeat the 1st point to easy make 4 edges.

**Comment by Philippe-Cholet** [comment]
@kurosawa4434 What do you think?

**Comment by Philippe-Cholet** [comment]
When user click on "Check", the function the user wrote now receives a list of tuples for argument. It is need because CheckiO use JSON at some point, and tuples were changed to lists. Most users would not have notice at all, but on principle.
###### I like visualization with matplotlib on local machine but it's better in external file.

**Pull request merged**
